name: Docker Image Build and Push To Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - '**/*' # This will trigger whenever there are changes in any file in the repository
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub WITH docker login credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Image tag with current date and timestamp
        id: get_datetime
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
      
      - name: Buil Docker image
        run: |
          docker build -t wisdom2608/wisdomtech:${{ steps.get_datetime.outputs.timestamp }} . # Replace with your image name
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push wisdom2608/wisdomtech:${{ steps.get_datetime.outputs.timestamp }} # Replace with your image name
