name: Docker Image Build and Push To Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - '**/*' # This will trigger whenever there are changes in any file in the repository
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login To Dockerhub With Dockerhub Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image With Current Date and Timestamp
        id: date_time
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
      
      - name: Build Docker Image
        run: |
          docker build -t wisdom2608/wisdomtech:${{ steps.date_time.outputs.timestamp }} . 
      
      - name: Push Docker Image To Dockerhub Repository
        run: |
          docker push wisdom2608/wisdomtech:${{ steps.date_time.outputs.timestamp }}

# There  two ways to update the image tag in the Kubernetes manifests file:
# a) Using sed command to find and replace the image tag in the Kubernetes manifest file direclty.
     
# # UPdate the K8s Manifest Files

#         # View the old k8s manifest (optional)
#       - name: Show Original Kubernetes Manifest
#         run:  |
#           cat manifests/deploy.yml

#       # Update the image tag in the Kubernetes manifest file (Required)
#       - name: Update Manifests with New Image Tag
#         run: |
#             sed -i "s|image: wisdom2608/wisdomtech:.*|image: wisdom2608/wisdomtech:${{  steps.date_time.outputs.timestamp }}|g" manifests/deploy.yml

#       # View the new k8s manifest after update (optional)
#       - name: Show Updated Kubernetes Manifest
#         run: cat manifests/deploy.yml


# b) Using find command to find and replace the image tag in the Kubernetes manifests file.

# UPdate the K8s Manifest Files

        # View the old k8s manifest before update(optional)
      - name: Show Original Kubernetes Manifest
        run:  |
          cat manifests/deploy.yml

      # Update the image tag in the Kubernetes manifest file (Required)
      - name:  Update image tag in manifests
        run: |
          find ./manifests -type f -name "deploy.yml" -exec sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/wisdomtech:.*|${{ secrets.DOCKERHUB_USERNAME }}/wisdomtech:${{ steps.date_time.outputs.timestamp }}|g" {} +

      # View the new k8s manifest after update (optional)
      - name: Show Updated Kubernetes Manifest
        run: cat manifests/deploy.yml




# Now that the image tag in the Kubernetes manifest file has been updated, we need to ....
# ..... update the repository or commit the changes to the repository.


# THERE ARE TWO WAYS TO UPDATE THE REPOSITORY:

# a) First Possibility.
      
    # # Update Github Repository.
    #   - name: Commit and push updated manifests
    #     run: |
    #       git config --global user.email "<>"
    #       git config --global user.name "GitHub Actions Bot"
    #       git add manifests/deploy.yml
    #       git commit -m "Update deploy.yaml with new image tag - ${{ steps.date_time.outputs.timestamp }}"
    #       git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/wisdom2608/application.git
    #       git push origin main


    # a) Second Possibility.

      - name: Commit and push updated manifests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Set remote URL using the GitHub token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

          git add .
          git commit -m "Update image tag to ${{ steps.date_time.outputs.timestamp }}" || echo "No changes to commit"
          git push

# Please Check The README.md File For More Detail