name: Docker Image Build and Push To Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - '**/*' # This will trigger whenever there are changes in any file in the repository
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login To Dockerhub With Dockerhub Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image With Current Date and Timestamp
        id: date_time
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
      
      - name: Build Docker Image
        run: |
          docker build -t wisdom2608/wisdomtech:${{ steps.date_time.outputs.timestamp }} . 
      
      - name: Push Docker Image To Dockerhub Repository
        run: |
          docker push wisdom2608/wisdomtech:${{ steps.date_time.outputs.timestamp }}

# UPdate the K8s Manifest Files

      - name: Show Original Kubernetes Manifest
        run:  |
          cat manifests/deploy.yml

      - name: Update Manifest with New Image Tag
        run: |
          sed -i "s|image: wisdom2608/wisdomtech:.*|image: wisdom2608/wisdomtech:${{  steps.date_time.outputs.timestamp }}|g" manifests/deploy.yml

      - name: Show Updated Kubernetes Manifest
        run: cat manifests/deploy.yml
# Now that the image tag in the Kubernetes manifest file has been updated, you we need to ....
# ..... update the repository as well.

      - name: Update image tag in manifest
        run: |

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          sed -i "s|wisdom2608/wisdomtech:.*|wisdom2608/wisdomtech:${{ steps.date_time.outputs.timestamp }}|g" manifests/deploy.yml
          git checkout -b update-image-${{ steps.date_time.outputs.timestamp }}
          git commit -am "Update image tag to ${{ steps.date_time.outputs.timestamp }}"
          git push origin update-image-${{ steps.date_time.outputs.timestamp }}