name: Docker Image Build and Push To Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - '**/*' # This will trigger whenever there are changes in any file in the repository
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login To Dockerhub With Dockerhub Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image With Current Date and Timestamp
        id: date_time
        run: echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
      
      - name: Build Docker Image
        run: |
          docker build -t wisdom2608/wisdomtech:${{ steps.date_time.outputs.timestamp }} . 
      
      - name: Push Docker Image To Dockerhub Repository
        run: |
          docker push wisdom2608/wisdomtech:${{ steps.date_time.outputs.timestamp }}

# UPdate the K8s Manifest Files

      - name: Show Original Kubernetes Manifest
        run:  |
          cat manifests/deploy.yml

# There  two ways to update the image tag in the Kubernetes manifests file:
# a) Using sed command to find and replace the image tag in the Kubernetes manifest file direclty.

# - name: Update Manifests with New Image Tag
      #   run: |
      #     sed -i "s|image: wisdom2608/wisdomtech:.*|image: wisdom2608/wisdomtech:${{  steps.date_time.outputs.timestamp }}|g" manifests/deploy.yml

# b) Using find command to find and replace the image tag in the Kubernetes manifests file.
      - name:  Update image tag in manifests
        run: |
          find ./manifests -type f -name "deploy.yml" -exec sed -i "s|${{ secrets.DOCKERHUB_USERNAME }}/wisdomtech:.*|${{ secrets.DOCKERHUB_USERNAME }}/wisdomtech:${{ steps.date_time.outputs.timestamp }}|g" {} +

      - name: Show Updated Kubernetes Manifest
        run: cat manifests/deploy.yml




# Now that the image tag in the Kubernetes manifest file has been updated, you we need to ....
# ..... update the repository as well.
      
    # Update Github
      - name: Commit the changes
        run: |
          git config --global user.email "mueatech087@gmail.com"
          git config --global user.name "GitHub Actions Bot"
          git add manifests/deploy.yml
          git commit -m "Update deploy.yaml with new image tag - ${{ steps.date_time.outputs.timestamp }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/wisdom2608/application.git
          git push origin main
  # Deploy to Kubernetes Cluster

